camunda:
  client:
    mode: self-managed
    auth:
      client-id: zeebe
      client-secret: nr4kGdMFy7
      token-url: http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://camunda-zeebe-gateway.default.svc.cluster.local:26500
