camunda:
  client:
    mode: self-managed
    auth:
      client-id: zeebe
      client-secret: nr4kGdMFy7
      token-url: http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://camunda-zeebe-gateway.default.svc.cluster.local:26500
#      ca-certificate-path: /app/certs/tls.crt
#      defaults:
#        use-case-retries: 5
#        retry-back-off: 3s
#        execution-threads: 1
#        max-jobs-active: 32
#        timeout: 10s
#        request-timeout: 10s
#        enabled: true
#        stream-enabled: false
